name: node-setup
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: node js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: check whether app running on 5000
        run: |
          npm i
          npm start &
          sleep 5
          curl -I http://localhost:3001 | grep "200 OK"

    


